SELECT now();
-- seed some owners

 INSERT INTO aruanded.props
  (id, entity, type, language, datatype, public, search,
    value_reference, value_text,
    created_at, created_by)
  VALUES
	(3,  '3','_mid',      NULL, 'string',  NULL, NULL,
    NULL, '3',
    NOW(), '4'),
	(4,  '4','_mid',      NULL, 'string',  NULL, NULL,
    NULL, '4',
    NOW(), '4'),
	(30, '3','_type',     NULL, 'string',  NULL, NULL,
    NULL, 'person',
    NOW(), '4'),
	(40, '4','_type',     NULL, 'string',  NULL, NULL,
    NULL, 'person',
    NOW(), '4'),
	(31, '3','name',      NULL, 'formula', NULL, 1,
    NULL, '@forename@ @surname@',
    NOW(), '4'),
	(41, '4','name',      NULL, 'formula', NULL, 1,
    NULL, '@forename@ @surname@',
    NOW(), '4'),
	(42, '4','email',     NULL, 'string',  0,    1,
    NULL, 'mihkel.putrinsh@gmail.com',
    NOW(), '4'),
	(32, '3','email',     NULL, 'string',  0,    1,
    NULL, 'argo@roots.ee',
    NOW(), '4'),
	(33, '3','entu_user', NULL, 'string',  0,    0,
    NULL, 'argoroots@gmail.com',
    NOW(), '4'),
	(43, '4','entu_user', NULL, 'string',  0,    0,
    NULL, 'mihkel.putrinsh@gmail.com',
    NOW(), '4'),
	(44, '4','forename',  NULL, 'string',  1,    1,
    NULL, 'Mihkel-Mikelis',
    NOW(), '4'),
	(34, '3','forename',  NULL, 'string',  1,    1,
    NULL, 'Argo',
    NOW(), '4'),
	(35, '3','phone',     NULL, 'string',  0,    1,
    NULL, '+37256630526',
    NOW(), '4'),
	(45, '4','phone',     NULL, 'string',  0,    1,
    NULL, '+37256560978',
    NOW(), '4'),
	(36, '3','photo',     NULL, 'file',    0,    0,
    NULL, 'A:argo.jpg\nB:8469afac40099272eab091f412114656\nC:template_2/3/9\nD:\nE:97107',
    NOW(), '4'),
	(46, '4','photo',     NULL, 'file',    0,    0,
    NULL, 'A:mihkel.gif\nB:e549ff6d284df921a0af991d998f530b\nC:template_2/4/10\nD:\nE:12933',
    NOW(), '4'),
	(47, '4','surname',   NULL, 'string',  1,    1,
    NULL, 'Putrinš',
    NOW(), '4'),
	(37, '3','surname',   NULL, 'string',  1,    1,
    NULL, 'Roots',
    NOW(), '4'),
	(38, '3', '_owner',   NULL, 'reference', 0, 0,
    '3', NULL,
    NOW(), '4'),
	(39, '3', '_owner',   NULL, 'reference', 0, 0,
    '4', NULL,
    NOW(), '4'),
	(48, '4', '_owner',   NULL, 'reference', 0, 0,
    '3', NULL,
    NOW(), '4'),
	(49, '4', '_owner',   NULL, 'reference', 0, 0,
    '4', NULL,
    NOW(), '4');
